# types of leaves randomly selected
leaves_sample:
    - "minecraft:oak_leaves"
    - "minecraft:birch_leaves"

# The log blocks used (ordered to match DIRECTIONS)
log_blocks:
    - "minecraft:oak_log"
    - "minecraft:oak_log[axis=z]"
    - "minecraft:oak_log[axis=z]"
    - "minecraft:oak_log[axis=x]"
    - "minecraft:oak_log[axis=x]"
    - "minecraft:oak_log"

# Horizontal log blocks
horizontal_log_blocks:
    - "minecraft:oak_log[axis=x]"
    - "minecraft:oak_log[axis=z]"

hanging_lantern: "minecraft:lantern[hanging=true]"

# the namespace of the functions
namespace: 'cloudtree/functions'
